drf/boards/APIView/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from discussion import views

# snippet_list = TopicList.as_view({
#     'get': 'list',
#     'post': 'create'
# })
# snippet_detail = TopicDetail.as_view({
#     'get': 'retrieve',
#     'put': 'update',
#     'patch': 'partial_update',
#     'delete': 'destroy'
# })


urlpatterns = [
    path('topic/', views.TopicList.as_view()),
    path('topic/<int:pk>/', views.TopicDetail.as_view()),    
]

urlpatterns = format_suffix_patterns(urlpatterns)

drf/boards/fbv/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from discussion import views

urlpatterns = [
    path('topic/', views.topic_list),
    path('topic/<int:pk>/', views.topic_detail),    
]

urlpatterns = format_suffix_patterns(urlpatterns)

drf/boards/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from boards import views

router = DefaultRouter()
router.register('board', views.BoardViewSet)
router.register('topic', views.TopicViewSet)
router.register('post', views.PostViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('', views.board_list,name='board-listview'), 
    path('<str:board_name>/', views.topic_list,name='board_topics'), 
]

drf/drf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import RedirectView

from .views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls')),
    path('', home_page ,name = "home_page"),
    #path('auth/', include('djoser.urls')),	
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

drf/boards/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.db import models


class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)    
    def __str__(self):
        return self.name
        
    def get_posts_count(self):        
        return Post.objects.filter(topic__board=self).count()
        
    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()

    def get_topics_count(self):
        return self.topics.count()
        

class Topic(models.Model):
    subject = models.CharField(max_length=255) 
    board = models.ForeignKey(Board, related_name='topics',on_delete=models.CASCADE)  
    description = models.TextField(max_length = 2000,default = "")    
    starter = models.ForeignKey(User, related_name='topics',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)  
    views = models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.subject	

    def get_post_count(self):
        return self.posts.count()        

    def get_last_post(self, obj):
        return Post.objects.filter(topic =self).order_by('-created_at').first()


class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.message

drf/boards/fbv/views.py
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .models import Topic
from .serializers import TopicSerializer

# Create your views here.




@api_view(['GET', 'POST'])
def topic_list(request, format=None):
    """
    List all code topics, or create a new topic.
    """
    if request.method == 'GET':
        topics = Topic.objects.all()
        serializer = TopicSerializer(topics, many=True)
        return Response(serializer.data)   
    elif request.method == 'POST':
        serializer = TopicSerializer(data = request.data)       
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



@api_view(['GET', 'PUT', 'DELETE'])
def topic_detail(request, pk, format=None):
    """
    Retrieve, update or delete a code snippet.
    """
    try:
        topic = Topic.objects.get(pk=pk)
    except Topic.DoesNotExist:
         return Response(status = status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = TopicSerializer(topic)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = TopicSerializer(topic, data = request.data)        
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        topic.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

drf/boards/views.py
from django.shortcuts import render
from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from .models import Board, Post, Topic
from .serializers import BoardSerializer, PostSerializer, TopicSerializer


class BoardViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list`, `create`, `retrieve`,
    `update` and `destroy` actions.

    Additionally we also provide an extra `highlight` action.
    """
    queryset = Board.objects.all()
    serializer_class = BoardSerializer



class TopicViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list`, `create`, `retrieve`,
    `update` and `destroy` actions.

    Additionally we also provide an extra `highlight` action.
    """
    queryset = Topic.objects.all()
    serializer_class = TopicSerializer

    #需要傳額外參數
    def perform_create(self, serializer):   
        serializer.save(starter=self.request.user)


    @action(detail=False,methods=['get'])
    def query_board_topic(self,request):
        board = request.query_params.get('board',None)  
        reviews = Topic.objects.filter(board__name = board).order_by('-start_date')
        serializer = TopicSerializer(reviews,many = True)
        return Response(serializer.data,status=status.HTTP_200_OK)


class PostViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list`, `create`, `retrieve`,
    `update` and `destroy` actions.

    Additionally we also provide an extra `highlight` action.
    """
    queryset = Post.objects.all()
    serializer_class = PostSerializer


    
    
def board_list(request):
    return render(request,"board/listview.html",{})


def topic_list(request,board_name):
    context = {}    
    context['board'] = Board.objects.get(name = board_name)
    return render(request,"topic/listview.html",context)

drf/boards/templates/topic/create.html
<div id="topic-modal-create" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="my-modal-title" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="user-modal-title">Create Topic</h5>
          <button class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form  method="post" data-url="/boards/api/topic/" class = "js-create-topic">
          {% csrf_token %}
        <div class="modal-body">
            <div name = "user-section">
              <label for="subject"> Subject</label>
              <input type="text" name="subject" maxlength="30" autofocus="" class="form-control" required>
            </div>
            <div name = "first_name-section">
              <label for="first_name"> Description</label>
              <textarea name="description" class="form-control" cols="40" rows="10" placeholder="What is on your mind?" maxlength="4000" required id="id_message"></textarea>
            </div>   
            <!-- <select class="form-control" name="board">            
              <option value="1">Python</option>        
            </select> -->
            
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Create</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </form>
      </div>
    </div>
  </div>

drf/boards/templates/topic/listview.html
{% extends "base.html" %}


    {% load static %}
    {% block stylesheet %}       
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-table.css' %}"> 
   
    {% endblock %}  
    {% block script %} 
    <script src="{% static 'js/bootstrap-table.min.js' %}"></script>
    
  
    
    
    {% endblock %}

                {% block content %}
                <h3>{{board}}</h3>  
                <div id="toolbar" style="float:right">
                  <button id="add" class="btn btn-primary">
                    <i class="fa fa-plus"></i> Add
                  </button>
                </div>
                {% include 'topic/create.html' %}
                <table id="topics-table"></table>
                <script src="{% static 'js/topic.js' %}"></script>
    <script>
     $(function() {
       initial("{{board.name}}","{{board.id}}")  
     })

      
    </script>
    {% endblock %}

drf/boards/templates/topic/update.html
<div id="user-update-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="my-modal-title" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="user-modal-title">Update</h5>
          <button class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="PATCH" data-url="" enctype="">
          {% csrf_token %}
        <div class="modal-body">
            <!-- <div name = "user-section">
              <label for="username"> Username</label>
              <input type="text" name="username" id = "username" maxlength="30" autofocus="" class="form-control" required>
            </div> -->
            <div name = "first_name-section">
              <label for="first_name"> First Name</label>
              <input type="text" name="first_name" id = "first_name" maxlength="30" autofocus="" class="form-control" required>
            </div>
            <div name = "last_name-section">
              <label for="last_name"> Last Name</label>
              <input type="text" name="last_name" id = "last_name" maxlength="30" autofocus="" class="form-control" required>
            </div>
            <div name = "email-section">
              <label for="email">Email</label>
              <input type="email" name="email" id = "email" maxlength="30" autofocus="" class="form-control" required>
            </div>                        
            <div name = "profile-cell_phone_number-section">
              <label for="profile.cell_phone_number">Cell Phone Number</label>
              <input type="text" name="profile.cell_phone_number" id = "cell_phone_number" maxlength="30" autofocus="" class="form-control" required>
            </div>  
            <div name = "profile-points-section">
              <label for="profile.points">Points</label>
              <input type="number" name="profile.points" id = "points" class="form-control" required>                           
            </div>  
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Update</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </form>
      </div>
    </div>
  </div>